### ISSUE TITLE
v1.1.1 No macros created.

### ISSUE THREAD

**Issue by sjay13** [SeaStove/GroundTargetMacros#5]
I am not seeing any macros being created in General or Character macros on any of my characters. I tried removing all existing macros as well as disabling all other addons. I have tried logging out and back in, switching specs, and /reload.

**Comment by AChubbyPanda** [comment]
Im getting the same issue as sjay13, macros no long get made

**Comment by novawulfe** [comment]
Ditto

**Comment by SeaStove** [comment]
looking into it now! Sorry looks like my github email settings werent working

**Comment by SeaStove** [comment]
Fixed in v1.2
