### ISSUE TITLE
Missing: Hunter Spells

### ISSUE THREAD

**Issue by novawulfe** [SeaStove/GroundTargetMacros#6]
Checked the code and pretty sure these 4 are missing.

Volley https://www.wowhead.com/spell=260243/volley
Implosive Trap https://www.wowhead.com/spell=462031/implosive-trap
Freezing Trap https://www.wowhead.com/spell=187650/freezing-trap
Tar Trap https://www.wowhead.com/spell=187698/tar-trap

**Comment by SeaStove** [comment]
looking into it now! Sorry looks like my github email settings werent working

**Comment by SeaStove** [comment]
Fixed in v1.2
