### ISSUE TITLE
Missing Spells: Thorough List

### ISSUE THREAD

**Issue by novawulfe** [SeaStove/GroundTargetMacros#8]
I play 39 max level alts, one for each spec in the game, so this addon really helps me, so I spent some time going through every alt and checking for missing spells, this is what I've found. (Only spec I couldn't test was fire mage as I'm waiting to make an earthen fire mage) I have included wowhead links for spell ids not sure if you need that but at least you can see the spell I am referencing.

**Shaman:**
Totemic Projection https://www.wowhead.com/spell=108287/totemic-projection

**Warlock:**
Demonic Gateway https://www.wowhead.com/spell=111771/demonic-gateway
Guillotine https://www.wowhead.com/spell=386833/guillotine

**Priest:**
Holy Word: Sanctify https://www.wowhead.com/spell=34861/holy-word-sanctify
Power Word: Barrier https://www.wowhead.com/spell=62618/power-word-barrier

**Paladin:**
Final Reckoning https://www.wowhead.com/spell=343721/final-reckoning

**Druid** - Incorrect spells and some talent specifics.
_-New:_
Efflorescence  https://www.wowhead.com/spell=145205/efflorescence

_-Existing:_
Starfall: Could be wrong on this but I don't think starfall needs a ground target as its aoe around you.
https://www.wowhead.com/spell=191034/starfall

Fury of Elune: Don't think Fury of Elune needs one as it requires a target to use and auto casts on them.
https://www.wowhead.com/spell=202770/fury-of-elune

Celestial Alignment/Incarnation: Chosen of Elune (Replaces it): If talented with Orbital Strike it becomes a ground target skill that casts a beam in a line towards where you click cursor.
https://www.wowhead.com/spell=194223/celestial-alignment
https://www.wowhead.com/spell=122114/chosen-of-elune
https://www.wowhead.com/spell=390378/orbital-strike

**Monk:**
Exploding Keg https://www.wowhead.com/spell=325153/exploding-keg

**Evoker:**
Deep Breath: Not sure if this is a ground target? But it uses a ground target to select a point to cast between you and where you click so im including it same as the druid Orbital Strike.
https://www.wowhead.com/spell=357210/deep-breath

Rescue: Again not sure if this counts but it uses a ground target for where to rescue your target too so I imagine it should be included.
https://www.wowhead.com/beta/spell=370665/rescue

Landslide: Same as Deep Breath/Orbital Strike, is a path to ground target skill.
https://www.wowhead.com/beta/spell=358385/landslide

**Comment by SeaStove** [comment]
Thank you so much this is extremely helpful! Including the link makes this way easier thank you, their ids are what I use to associate them. I'll update the add on tonight with your new additions!

**Comment by SeaStove** [comment]
Resolved with v1.2.1, thanks again!

**Comment by novawulfe** [comment]
No problem, happy to help, thanks for the addon :D
